version: "3"
services:
  auto-browser:
    image: harleyliu/auto-browser:latest
    restart: always
    build: ./auto-browser
    environment:
      - HEADLESS=$HEADLESS
      - ENABLE_CLICK=$ENABLE_CLICK
      - ADNADE_USERNAME=$ADNADE_USERNAME
      - ADNADE_PASSWORD=$ADNADE_PASSWORD
      - EBESUCHER_USERNAME=$EBESUCHER_USERNAME
      - SURFVISITS_USERNAME=$SURFVISITS_USERNAME
      - SURFVISITS_PASSWORD=$SURFVISITS_PASSWORD
    volumes:
      - ./data/auto-browser:/app/data
    network_mode: service:tun2socks

  bitping:
    image: bitping/bitpingd:latest
    restart: always
    environment:
      - BITPING_EMAIL=$BITPING_EMAIL
      - BITPING_PASSWORD=$BITPING_PASSWORD
    volumes:
      - ./data/bitpingd:/root/.bitpingd
    network_mode: service:tun2socks

  earnapp:
    image: madereddy/earnapp:latest
    restart: always
    environment:
      - EARNAPP_UUID=$EARNAPP_UUID
    network_mode: service:tun2socks

  earnfm:
    image: earnfm/earnfm-client:latest
    restart: always
    environment:
      - EARNFM_TOKEN=$EARNFM_TOKEN
    network_mode: service:tun2socks

  feelingsurf:
    image: feelingsurf/viewer:stable
    restart: always
    environment:
      - access_token=$FEELINGSURF_TOKEN
    network_mode: service:tun2socks

  grass:
    image: alone/grass:latest
    restart: always
    ports:
      - 8082:8080
    environment:
      - VNC_PASS=$VNC_PASS
    network_mode: service:tun2socks

  honeygain:
    image: honeygain/honeygain:latest
    restart: always
    command: -tou-accept -email $HONEYGAIN_EMAIL -pass '$HONEYGAIN_PASSWD' -device $DEVICE_NAME
    network_mode: service:tun2socks

  packetshare:
    image: packetshare/packetshare:latest
    restart: always
    command: -accept-tos -email=$PACKETSHARE_EMAIL -password=$PACKETSHARE_PASSWORD
    network_mode: service:tun2socks

  packetstream:
    image: packetstream/psclient:latest
    restart: always
    environment:
      - CID=$PACKETSTREAM_CID
    network_mode: service:tun2socks

  pawnsapp:
    image: iproyal/pawns-cli:latest
    restart: always
    command: -email=$PAWNSAPP_EMAIL -password=$PAWNSAPP_PASSWD -device-name=$DEVICE_NAME -device-id=$DEVICE_NAME -accept-tos
    network_mode: service:tun2socks

  proxylite:
    image: proxylite/proxyservice:latest
    restart: always
    environment:
      - USER_ID=$PROXYLITE_USER_ID
    network_mode: service:tun2socks

  proxyrack:
    image: proxyrack/pop:latest
    restart: always
    environment:
      - UUID=$PROXYRACK_UUID
    network_mode: service:tun2socks

  repocket:
    image: repocket/repocket:latest
    restart: always
    environment:
      - RP_EMAIL=$REPOCKET_EMAIL
      - RP_API_KEY=$REPOCKET_API_KEY
    network_mode: service:tun2socks

  speedshare:
    image: mrcolorrain/speedshare:latest
    restart: always
    environment:
      - CODE=$SPEEDSHARE_TOKEN
    network_mode: service:tun2socks

  spidenetwork:
    image: xterna/spide-network:latest
    restart: always
    network_mode: service:tun2socks

  TraffMonetizer:
    image: traffmonetizer/cli_v2:latest
    restart: always
    command: start accept --token $TRAFFMONETIZER_TOKEN
    network_mode: service:tun2socks

  tun2socks:
      image: xjasonlyu/tun2socks:latest
      restart: always
      command: ["/bin/sh", "-c", "echo 'nameserver 1.1.1.1\nnameserver 8.8.8.8' > /etc/resolv.conf && ip rule add iif lo ipproto udp dport 53 lookup main && ip rule add iif lo ipproto udp dport 3478 lookup main"]
      environment:
          - LOGLEVEL=info
          - PROXY=$PROXY
      volumes:
          - /dev/net/tun:/dev/net/tun
      cap_add:
          - NET_ADMIN
